FROM alpine:edge

RUN echo '@testing http://nl.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories && \
    echo '@community http://nl.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories && \
    apk --update add \
        php7@community \
        php7-dom@community \
        php7-ctype@community \
        php7-curl@community \
        php7-fpm@community \
        php7-gd@community \
        php7-intl@community \
        php7-json@community \
        php7-mbstring@community \
        php7-mcrypt@community \
        php7-mysqlnd@community \
        php7-opcache@community \
        php7-pdo@community \
        php7-pdo_mysql@community \
        php7-posix@community \
        php7-session@community \
        php7-xml@community \
        php7-iconv@community \
        php7-phar@community \
        php7-openssl@community \
        php7-xdebug@community \
        php7-redis@testing \
    && rm -rf /var/cache/apk/*

COPY php/php.ini /etc/php7/conf.d/50-setting.ini
COPY php/php-fpm.conf /etc/php7/php-fpm.conf

RUN ln -s /usr/bin/php7 /usr/bin/php
RUN ln -s /usr/sbin/php-fpm7 /usr/bin/php-fpm

EXPOSE 9000

RUN chmod 755 /root

# cleanup
RUN rm -rf /var/cache/apk/* /tmp/* /usr/share/man

CMD ["php-fpm7", "-F"]