# Use Alpine Linux
FROM alpine:latest

# Declare maintainer
MAINTAINER Radosław Zagórski <r@zagorski.it>

# Timezone
ENV TIMEZONE Europe/Warsaw

# Let's roll
RUN	apk update && \
	apk upgrade && \
	apk add --update openssl nginx && \
	apk add --update tzdata && \
	cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && \
	echo "${TIMEZONE}" > /etc/timezone && \
	mkdir /etc/nginx/certificates && \
	openssl req \
		-x509 \
		-newkey rsa:2048 \
		-keyout /etc/nginx/certificates/key.pem \
		-out /etc/nginx/certificates/cert.pem \
		-days 365 \
		-nodes \
		-subj /CN=localhost && \
	mkdir /www && \
	apk del tzdata && \
	rm -rf /var/cache/apk/*

COPY ./nginx/etc/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/etc/common.conf /etc/nginx/common.conf
COPY ./nginx/etc/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/etc/conf.d/ssl.conf /etc/nginx/conf.d/ssl.conf

# Expose ports
EXPOSE 80 443

# Entry point
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]