version: '2'

services:

  nginx:
    container_name: nginx_alpine
    build:
      context: .
      dockerfile: dockerfile-nginx
    depends_on:
      - phpfpm
    ports:
      - 8080:80
    links:
      - phpfpm
    volumes:
      - ./logs/nginx:/var/log/nginx

  phpfpm:
    container_name: phpfpm
    build:
      context: .
      dockerfile: dockerfile-php
    links:
      - redis
      - mysql
    ports:
      - 9000:9000
    volumes:
      - ./www:/usr/share/nginx

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes_from:
      - appdata
    environment:
      MYSQL_ROOT_PASSWORD: example

  linux:
    container_name: linux
    build:
      context: .
      dockerfile: dockerfile-linux
    links:
      - phpfpm
    volumes:
      - ./html:/usr/share/nginx/html

  appdata:
    container_name: db-data
    image: busybox:latest
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  db-data:
